name: build

on: [push, pull_request]

jobs:
  check-opam-sanity:
    name: Check sanity of opam/Satyristes
    runs-on: ubuntu-latest
    container:
      image: amutake/satysfi:0.0.5
    steps:
      - uses: actions/checkout@v2
      - name: Try to install arrows and arrows-doc
        run: |
          export HOME=/root
          eval $(opam env)
          opam update
          opam pin add "file://${PWD}"
          satyrographos install -l arrows -l arrows-doc
